### ISSUE TITLE
tangoJobManager looping after docker-compose up

### ISSUE THREAD

**Issue by carlosnatalino** [autolab/docker#10]
Hi,

I am installing this for the first time, and when I take step 6 Run the containers: `docker-compose up`, everything seems to be working, except the tangoJobManager, which seems to be looping.

The message that I get is as follows:

```
tango      | 2020-10-22 17:27:54,917 INFO success: tangoJobManager entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tango      | 2020-10-22 17:27:54,919 INFO spawned: 'tango' with pid 126
tango      | 2020-10-22 17:27:55,920 INFO success: tango entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tango      | 2020-10-22 17:27:59,065 INFO exited: tangoJobManager (exit status 1; not expected)
```

This sequence of messages keeps appearing. It seems to be encountering some problem during initialization.

Can you help me with this?

**Comment by fanpu** [comment]
Hi @carlosnatalino, thanks for flagging this issue! The reason is due to a config error on our side, we will get it fixed soon. The issue is because REDIS_HOSTNAME is set incorrectly. If you change REDIS_HOSTNAME in config.template.py to "redis", it should work.

**Comment by carlosnatalino** [comment]
Hi @fanpu, great! I tried the change you suggested and got it to work! Thanks!
