### ISSUE TITLE
Failed due to Autolab dependencies 

### ISSUE THREAD

**Issue by thomasbra1** [autolab/docker#34]
I am attempting to install the current docker version and run into this issue in the Autolab folder

 ---> Running in 142f1a15f1f8
Required ruby-2.6.6 is not installed.
To install do: 'rvm install "ruby-2.6.6"'
Warning: the running version of Bundler (1.17.2) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.6.7, but your Gemfile specified 2.6.6
The command '/bin/sh -c bundle install' returned a non-zero code: 18
ERROR: Service 'autolab' failed to build : Build failed

Trying to bump this to 2.6.7 in the Gemfile causes even more depedency issues.

**Comment by ashleyzhang** [comment]
Hi! The above change should fix this issue once it's merged, but in the meantime you can change line 10 in Autolab/Dockerfile from `FROM phusion/passenger-ruby26` to `FROM phusion/passenger-ruby26:1.0.13` and try rerunning `docker-compose build`. Let us know if you run into more issues! Also, please feel free to join our [Slack workspace](https://autolab-slack.herokuapp.com/) as another resource.

**Comment by thomasbra1** [comment]
Hello

That got much further but stopped at this point.

Step 12/24 : USER app
 ---> Running in 05015d70ad24
Removing intermediate container 05015d70ad24
 ---> 70ce2327c222
Step 13/24 : RUN bundle install
 ---> Running in 80913ea4f24d
Fetching gem metadata from https://rubygems.org/.........
Your bundle is locked to mimemagic (0.3.5), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.5) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
in order to install.
The command '/bin/sh -c bundle install' returned a non-zero code: 7
ERROR: Service 'autolab' failed to build : Build failed

**Comment by ashleyzhang** [comment]
Could you check to make sure your Gemfile.lock is up-to-date with the most recent Autolab changes? It should be locked to version 0.4.2 instead of 0.3.5 since [this fix](https://github.com/autolab/Autolab/pull/1347).

**Comment by thomasbra1** [comment]
I pulled a fresh copy using the git command from the docker documentation that is linked here and made sure made sure there were no leftover docker containers from any earlier runs.   I do notice that this github links to the November 14th, 2020 git (Autolab @ 9a86b5c)and not the latest version of Autolab which would contain the fix you mentioned above.  The Tango link is also older.

**Comment by thomasbra1** [comment]
I am able to complete the build but have run into issues with the make create-user step.

bob@bobu2024:~/autolab/autolab-docker$ make create-user
docker exec -it autolab bash /home/app/webapp/docker/initialize_user.sh
bash: /home/app/webapp/docker/initialize_user.sh: No such file or directory
make: *** [Makefile:49: create-user] Error 127


.PHONY: create-user
create-user:
        docker exec -it autolab bash /home/app/webapp/docker/initialize_user.sh

I looked at the container from its shell and the initialize_user.sh is not in that location.  

The script is now located at /home/app/webapp/bin in the container.  

I changed the Makefile to point to this location and ran the command again but then this error

bob@bobu2024:~/autolab/autolab-docker$ make create-user
docker exec -it autolab bash /home/app/webapp/bin/initialize_user.sh
############## Initialize a new root user ##############
User Email: test@test.com
Password: 
Confirm Password: 
First Name: Test
Last Name: Test
rails aborted!
SocketError: getaddrinfo: Name or service not known
/usr/local/rvm/gems/ruby-2.6.6/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/usr/local/rvm/gems/ruby-2.6.6/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/usr/local/rvm/gems/ruby-2.6.6/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/usr/local/rvm/gems/ruby-2.6.6/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionmailer-5.2.0/lib/action_mailer/base.rb:560:in `block in deliver_mail'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionmailer-5.2.0/lib/action_mailer/base.rb:558:in `deliver_mail'
/usr/local/rvm/gems/ruby-2.6.6/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionmailer-5.2.0/lib/action_mailer/message_delivery.rb:114:in `block in deliver_now'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionmailer-5.2.0/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionmailer-5.2.0/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/usr/local/rvm/gems/ruby-2.6.6/gems/devise-4.7.1/lib/devise/models/authenticatable.rb:199:in `send_devise_notification'
/usr/local/rvm/gems/ruby-2.6.6/gems/devise-4.7.1/lib/devise/models/confirmable.rb:121:in `send_confirmation_instructions'
/usr/local/rvm/gems/ruby-2.6.6/gems/devise-4.7.1/lib/devise/models/confirmable.rb:183:in `send_on_create_confirmation_instructions'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:261:in `block in conditional'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:517:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:517:in `invoke_after'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:133:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:816:in `_run_commit_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/transactions.rb:345:in `committed!'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:119:in `commit_records'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:214:in `block in commit_transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:204:in `commit_transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:243:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/transactions.rb:383:in `with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/transactions.rb:310:in `block in save'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/transactions.rb:309:in `save'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/suppressor.rb:44:in `save'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/active_record_prepend.rb:16:in `block in save'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent.rb:678:in `with_database_metric_name'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/active_record_prepend.rb:15:in `save'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/persistence.rb:36:in `create'
/home/app/webapp/lib/tasks/admin.rake:31:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => admin:create_root_user
(See full trace by running task with --trace)
make: *** [Makefile:49: create-user] Error 1

**Comment by fanpu** [comment]
Confirm that I can replicate this, looking into it

**Comment by fanpu** [comment]
Could you run `make update` to get the latest Autolab, rebuild the containers and try again?

**Comment by thomasbra1** [comment]
Hello,

I was able to pull and create a new users.  

I find this step confusing in the documentation:

**Change DOCKER_TANGO_HOST_VOLUME_PATH in docker-compose.yml to be the absolute path to the Tango volumes directory, i.e /<path-to-docker-compose-installation>/Tango/volumes. This is so that Tango knows where to put the output files of its autograded jobs.


# in docker-compose.yml

# Modify the below to be the path to volumes on your host machine
- DOCKER_TANGO_HOST_VOLUME_PATH=/home/your-user/autolab-docker/Tango/volumes # example path**


When saying volumes is it talking about Docker volumes or just a directory on the host machine?  

On my host it creates the following volumes:

ob@bobu2024:~/autolab/autolab-docker$ docker volume ls
DRIVER    VOLUME NAME
local     7a531921105cde1043c2a61de46e7fc94fcbad065540c5930758d11feb82b17c
local     95f69e1b5e98d3825cc711251972cafd282bec1eea2556519afcac57cf61e308
local     130775db3b11fb30c608be12715519a2f353aa53cc7ba15b2e651f3d4ba10900

It is talking about one of these volumes?

Thanks.

**Comment by thomasbra1** [comment]
I was able to pull and create a new users.

I find this step confusing in the documentation:

Change DOCKER_TANGO_HOST_VOLUME_PATH in docker-compose.yml to be the absolute path to the Tango volumes directory, i.e //Tango/volumes. This is so that Tango knows where to put the output files of its autograded jobs.

in docker-compose.yml
Modify the below to be the path to volumes on your host machine
DOCKER_TANGO_HOST_VOLUME_PATH=/home/your-user/autolab-docker/Tango/volumes # example path
When saying volumes is it talking about Docker volumes or just a directory on the host machine?

On my host it creates the following volumes:

ob@bobu2024:~/autolab/autolab-docker$ docker volume ls
DRIVER VOLUME NAME
local 7a531921105cde1043c2a61de46e7fc94fcbad065540c5930758d11feb82b17c
local 95f69e1b5e98d3825cc711251972cafd282bec1eea2556519afcac57cf61e308
local 130775db3b11fb30c608be12715519a2f353aa53cc7ba15b2e651f3d4ba10900

It is talking about one of these volumes?

Thanks.

**Comment by fanpu** [comment]
Sorry about the late response, this is supposed to be a directory on the host machine. 

The reason for that is because we are mapping the Docker socket into the Tango container so that we can re-use the host's Docker instance and not have to run docker-in-docker, which is inefficient. However, this means that the docker instance (which belongs to the host) actually needs a path that is relative to the host, instead of the container.

**Comment by thomasbra1** [comment]
Thanks for the clarification.  Things look good now.  Thanks to both you and Angela for working so quickly to fix issues.
Brad

**Comment by fanpu** [comment]
Thank you for reporting the issue as well! Do reach out anytime in the future if you run into things again, and we have a pretty active community on [Slack](https://autolab-slack.herokuapp.com/) as well.
