### ISSUE TITLE
State minimum docker-compose version necessary

### ISSUE THREAD

**Issue by carlosnatalino** [autolab/docker#9]
I have found out that the docker-compose file version 3.8, which is used here, is only available from version 1.25.5. My Ubuntu apt installed version 1.17.1, and wasn't working with the docker-compose file.

The announcement of the file version 3.8 can be seen here: https://github.com/docker/compose/releases/tag/1.25.5

I suggest stating the minimum version to avoid confusion.

**Comment by fanpu** [comment]
Just to check, are you on Ubuntu 18.04? It shows the same version on my Ubuntu 18.04 server. 

I agree with you that we are not using any of the latest features, and since we are targeting Ubuntu 18.04 as well for this installation this should be changed

**Comment by carlosnatalino** [comment]
Hi @fanpu, yes, I'm using Ubuntu 18.04. I agree with your approach to solving this issue. Thanks!
